// GENERATED by tools/bake-terrain.mjs - do not edit by hand (re-run the baker).
// Photoscanned ground materials (CC0, Poly Haven / ambientCG): layer stacks per biome,
// repeat scales and mean colours (linear RGB). Files: public/tex/terrain/<size>/<key>_{a,n}.webp.

export type PhotoSlot = 'grass' | 'dirt' | 'rock' | 'sand' | 'mud' | 'forest' | 'gravel' | 'soil' | 'snow' | 'asphalt' | 'paving';

export interface PhotoMaterial {
  /** Map tiles per texture repeat. */
  tiles: number;
  /** Man-made pattern: no random rotation when anti-tiling. */
  regular: boolean;
  /** Mean albedo, linear RGB. */
  mean: [number, number, number];
  /** Mean albedo, sRGB hex. */
  hex: number;
  /** Mean roughness. */
  rough: number;
}

export interface PhotoStack {
  /** Material keys in array-layer order. */
  layers: string[];
  /** Shader slot -> array layer. */
  slot: Record<PhotoSlot, number>;
  /** Download size per texture size (both WebPs of every layer). */
  bytes: Record<number, number>;
}

export const PHOTO_SIZES = [512,1024];

export const PHOTO_MATERIALS: Record<string, PhotoMaterial> = {
  meadow: { tiles: 2.4, regular: false, mean: [0.1176, 0.1486, 0.0321], hex: 0x606c32, rough: 0.86 },
  withered: { tiles: 2.4, regular: false, mean: [0.3879, 0.2784, 0.1854], hex: 0xa79077, rough: 0.808 },
  litter: { tiles: 2.6, regular: false, mean: [0.2441, 0.1495, 0.0491], hex: 0x876c3f, rough: 0.933 },
  dirt: { tiles: 2.6, regular: false, mean: [0.1198, 0.0816, 0.0468], hex: 0x61513d, rough: 0.944 },
  drysoil: { tiles: 2.8, regular: false, mean: [0.2356, 0.1387, 0.065], hex: 0x856848, rough: 0.812 },
  gravel: { tiles: 2.2, regular: false, mean: [0.2477, 0.186, 0.1263], hex: 0x887764, rough: 0.82 },
  mossrock: { tiles: 5, regular: false, mean: [0.1555, 0.11, 0.0468], hex: 0x6e5d3d, rough: 0.817 },
  sandstone: { tiles: 3.4, regular: false, mean: [0.5534, 0.3118, 0.1556], hex: 0xc4986e, rough: 0.908 },
  snowrock: { tiles: 3.2, regular: false, mean: [0.199, 0.1714, 0.1464], hex: 0x7b736b, rough: 0.714 },
  greyrock: { tiles: 3.2, regular: false, mean: [0.3853, 0.3266, 0.2627], hex: 0xa79b8c, rough: 0.78 },
  beach: { tiles: 4.5, regular: false, mean: [0.2214, 0.1696, 0.1073], hex: 0x81725c, rough: 0.963 },
  dunes: { tiles: 6, regular: false, mean: [0.2424, 0.2032, 0.1679], hex: 0x877c72, rough: 0.9 },
  mud: { tiles: 2.2, regular: false, mean: [0.0721, 0.0568, 0.0378], hex: 0x4c4337, rough: 0.952 },
  cracked: { tiles: 2.4, regular: false, mean: [0.561, 0.3573, 0.2009], hex: 0xc5a17c, rough: 0.756 },
  farmsoil: { tiles: 2.2, regular: false, mean: [0.088, 0.046, 0.0194], hex: 0x543d26, rough: 0.976 },
  snow: { tiles: 3.4, regular: false, mean: [0.2936, 0.2932, 0.3011], hex: 0x939395, rough: 0.801 },
  asphalt: { tiles: 2.4, regular: false, mean: [0.1002, 0.0987, 0.088], hex: 0x595854, rough: 0.77 },
  pavement: { tiles: 2, regular: true, mean: [0.1972, 0.1627, 0.1247], hex: 0x7b7063, rough: 0.862 },
  rubble: { tiles: 2.2, regular: false, mean: [0.3358, 0.2736, 0.2327], hex: 0x9d8f85, rough: 0.895 },
  flags: { tiles: 2.4, regular: true, mean: [0.1679, 0.1289, 0.0809], hex: 0x726550, rough: 0.777 },
};

export const PHOTO_STACKS: Record<'temperate' | 'desert' | 'winter' | 'urban', PhotoStack> = {
  temperate: { layers: ["meadow","dirt","mossrock","beach","mud","litter","gravel","farmsoil"], slot: {grass: 0,dirt: 1,rock: 2,sand: 3,mud: 4,forest: 5,gravel: 6,soil: 7,snow: 3,asphalt: 2,paving: 1}, bytes: {512: 1340216,1024: 4856604} },
  desert: { layers: ["withered","drysoil","sandstone","dunes","cracked","gravel","farmsoil"], slot: {grass: 0,dirt: 1,rock: 2,sand: 3,mud: 4,gravel: 5,soil: 6,forest: 1,snow: 3,asphalt: 2,paving: 1}, bytes: {512: 1112392,1024: 3963898} },
  winter: { layers: ["withered","dirt","snowrock","snow","mud","litter","gravel","farmsoil"], slot: {grass: 0,dirt: 1,rock: 2,sand: 3,mud: 4,forest: 5,gravel: 6,soil: 7,snow: 3,asphalt: 2,paving: 1}, bytes: {512: 1289062,1024: 4810664} },
  urban: { layers: ["meadow","pavement","greyrock","rubble","mud","gravel","asphalt","flags"], slot: {grass: 0,dirt: 1,rock: 2,sand: 3,mud: 4,gravel: 5,asphalt: 6,paving: 7,forest: 1,soil: 1,snow: 3}, bytes: {512: 979256,1024: 3707832} },
};

/** Tree barks (atlas cells), 256 px albedo. */
export const PHOTO_BARKS = {"oak":{"bytes":13246,"mean":[0.1264,0.1035,0.0608]},"pine":{"bytes":15772,"mean":[0.1386,0.089,0.0541]},"palm":{"bytes":12654,"mean":[0.0993,0.0763,0.0598]}} as const;

/** Sky HDRIs (RGBE in lossless WebP, 512 x 256): sun position (equirect u / v), hemisphere means (linear). */
export const PHOTO_HDRIS = {"clear":{"bytes":216384,"sun":{"u":0.3022,"v":0.0244,"elev":85.6},"sky":[0.1801,0.2665,0.5951],"ground":[0.1391,0.2008,0.0774]},"overcast":{"bytes":192582,"sun":{"u":0.4673,"v":0.3076,"elev":34.6},"sky":[1.2373,1.2219,1.2197],"ground":[0.0379,0.0297,0.0241]},"sunset":{"bytes":248900,"sun":{"u":0.5991,"v":0.4814,"elev":3.3},"sky":[1.0164,1.2094,1.5016],"ground":[0.1138,0.1377,0.0762]}} as const;
